language: node_js
addons:
  code_climate:
    repo_token: c531c8e5071ed9beed5368987fc03f8500b2854a0bddd6bae81a516c34584118 
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive --require ./test/setup.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
  - rm -rf ./coverage
